# event types
TRIGGERS = ['MOVEMENT-UP-GAIN', 'CAUSE-MOVEMENT-DOWN-LOSS', 'MOVEMENT-DOWN-LOSS', 'CIVIL-UNREST', 'EMBARGO', 'SLOW-WEAK',
            'CAUSE-MOVEMENT-UP-GAIN','GROW-STRONG', 'GEOPOLITICAL-TENSION','OVERSUPPLY','SHORTAGE', 'PROHIBITING', 
            'MOVEMENT-FLAT', 'SITUATION_DETERIORATE', 'TRADE-FINANCIAL-TENSION', 'POSITION-HIGH', 'POSITION-LOW',
            'NEGATIVE_SENTIMENT', 'CRISIS']
            
            
# Polarity & Modality
POLARITY = ['POSITIVE', 'NEGATIVE']
MODALITY = ['ASSERTED', 'OTHER']
INTENSITY = ['NEUTRAL', 'EASED', 'INTENSIFIED']

PRICE = ['UP', 'DOWN']